const Data = {
  studyContent2024_1_1: [
    { week: "1주차", topic: "입출력, 변수, 연산자, 자료형" },
    { week: "2주차", topic: "조건문, 반복문, 빠른 입출력" },
    { week: "3주차", topic: "문자열" },
    { week: "4주차", topic: "리스트" },
    { week: "5주차", topic: "브루트포스" },
    { week: "6주차", topic: "딕셔너리, 셋" },
    { week: "7주차", topic: "함수, 재귀함수" },
    { week: "8주차", topic: "기초 내부 대회" },
  ],
  studyContent2024_1_2: [
    { week: "1주차", topic: "입출력, 변수, 연산자, 자료형" },
    { week: "2주차", topic: "조건문, 반복문, 빠른 입출력" },
    { week: "3주차", topic: "문자열" },
    { week: "4주차", topic: "리스트" },
    { week: "5주차", topic: "브루트포스" },
    { week: "6주차", topic: "딕셔너리, 셋" },
    { week: "7주차", topic: "함수, 재귀함수" },
    { week: "8주차", topic: "기초 내부 대회" },
  ],
  studyContent2024_2_1: [
    { week: "1주차", topic: "입출력, 변수, 연산자, 자료형" },
    { week: "2주차", topic: "조건문, 반복문, 빠른 입출력" },
    { week: "3주차", topic: "문자열" },
    { week: "4주차", topic: "리스트" },
    { week: "5주차", topic: "브루트포스" },
    { week: "6주차", topic: "딕셔너리, 셋" },
    { week: "7주차", topic: "함수, 재귀함수" },
    { week: "8주차", topic: "기초 내부 대회" },
  ],
  studyContent2024_2_2: [
    { week: "1주차", topic: "입출력, 변수, 연산자, 자료형" },
    { week: "2주차", topic: "조건문, 반복문, 빠른 입출력" },
    { week: "3주차", topic: "문자열" },
    { week: "4주차", topic: "리스트" },
    { week: "5주차", topic: "브루트포스" },
    { week: "6주차", topic: "딕셔너리, 셋" },
    { week: "7주차", topic: "함수, 재귀함수" },
    { week: "8주차", topic: "기초 내부 대회" },
  ],
  studyContent2024_2_3: [
    { week: "1주차", topic: "입출력, 변수, 연산자, 자료형" },
    { week: "2주차", topic: "조건문, 반복문, 빠른 입출력" },
    { week: "3주차", topic: "문자열" },
    { week: "4주차", topic: "리스트" },
    { week: "5주차", topic: "브루트포스" },
    { week: "6주차", topic: "딕셔너리, 셋" },
    { week: "7주차", topic: "함수, 재귀함수" },
    { week: "8주차", topic: "기초 내부 대회" },
  ],
};

export default Data;
