const CellType = {
  CIRCLE: "CIRCLE",
  CIRCLE_WITH_TEXT: "CIRCLE_WITH_TEXT",
  CIRCLE_WITH_ICON: "CIRCLE_WITH_ICON",
  BUTTON: "BUTTON",
  HORIZONTAL_RECTANGLE: "HORIZONTAL_RECTANGLE",
  LONG_HORIZONTAL_RECTANGLE: "LONG_HORIZONTAL_RECTANGLE",
  VERTICAL_RECTANGLE: "VERTICAL_RECTANGLE",
  TEXT: "TEXT",
  CURVE: "CURVE",
  ANIMATE_CURVE: "ANIMATE_CURVE",
  ANIMATE_CURVE_WITH_DELAY: "ANIMATE_CURVE_WITH_DELAY",
};

export default CellType;
