name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository checkout
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Node.js 버전은 프로젝트에 맞게 변경

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build project
      - name: Build Project
        run: npm run build # build 스크립트는 프로젝트에 맞게 변경

      # 5. Ensure build directory exists and move output to dist folder
      - name: Move Build Output to Dist
        run: |
          if [ -d "./build" ]; then
            mkdir -p dist
            mv ./build/* ./dist/
          else
            echo "Build directory not found. Check your build step and output path."
            exit 1
          fi

      # 6. Set up Firebase Authentication
      - name: Set up Firebase Authentication
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > serviceAccountKey.json

      # 7. Deploy to Firebase
      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project your-project-id
        env:
          GOOGLE_APPLICATION_CREDENTIALS: serviceAccountKey.json
